version: '3.2'
services:
  # Client app
  web:
    container_name: web
    image: ferdiardiansa/social-media:latest
    ports:
      - 3007:80
    networks: 
      - sh-client
    volumes:
      - client-app-data:/usr/share/nginx/html
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  # Client web server
  client-web-server:
    container_name: sh-client-web-server
    build:
      context: .
      dockerfile: '.docker/client-web-server/Dockerfile'
      cache_from:
        - nginx:latest
      args:
        - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:80
    volumes:
      - ./logs/client-web-server/:/var/log/nginx
    restart: always
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - sh-client
    volumes:
      - client-app-data:/usr/app
    deploy:
      replicas: 2

networks:
  sh-client:

volumes:
  client-app-data:
